language: python
cache: pip

install: pip install tox
script: tox

matrix:
  include:
    - env: TOXENV=black
    - env: TOXENV=flake8
    - env: TOXENV=isort
    - env: TOXENV=mypy
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
