dist: xenial
sudo: false
language: python
cache: pip

install: pip install tox
script: tox

matrix:
  include:
    - python: "3.6"
      env: TOXENV=black
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=isort
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
