name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install coveralls tox

      - name: Run tests
        run: tox
